### ISSUE TITLE
小游戏

### ISSUE THREAD

**Issue by duola8789** [10cella/weapp.socket.io#14]
小游戏中不能使用?
在小程序中使用没有问题，在小游戏官方提供的打飞机游戏里面使用，没有报错，但是也没有简历websocket连接

**Comment by gongzili456** [comment]
方便贴一下代码片段吗？

**Comment by jimmyyao88** [comment]
同样的问题 在小游戏下 没有建立socket 连接 
在调试工具里看网络没有任何请求被发送
`
this.socket = io('http://127.0.0.1:5000')
    this.socket.on('connect', () => {
      console.log('连接成功')
    })

    this.socket.on('connect_error', d => {
      console.log('失败')
    })

    this.socket.on('connect_timeout', d => {
      console.log('超时')
    })

    this.socket.on('disconnect', reason => {
    })
`
