### ISSUE TITLE
真机报closeSoceket:failWebSocket is not connectecd,开发工具没报错，用的是wxapp-socket-io版本

### ISSUE THREAD

**Issue by qappleh** [10cella/weapp.socket.io#18]
![image](https://user-images.githubusercontent.com/8843764/44636490-a8862e80-a9de-11e8-8d47-d60d1a2661f6.png)

**Comment by gongzili456** [comment]
请先排除 Server 端的连接问题，然后查看是否需要勾选 取消https 和域名校验。最后推荐使用 [weapp.socket.io](https://github.com/weapp-socketio) 版本，原来的 wxapp-socket-io 已经不再维护。
