### ISSUE TITLE
Error] 找不到文件:  xxxx/node_modules/weapp.engine.io/lib/transports/polling-xhr

### ISSUE THREAD

**Issue by notedit** [10cella/weapp.socket.io#2]
在wepy中使用weapp.socket.io  会提示找不到polling-xhr

搜索了weapp.socket.io  和  weapp.engine.io,  并没有发现有引入这个文件的地方.

目前不清楚为什么找不到该文件

**Comment by yy197133** [comment]
你都用了wepy了，干嘛还用weapp.socket.io?

**Comment by notedit** [comment]
@yy197133  服务端用的socketio  要跟其他平台打通

**Comment by gongzili456** [comment]
@notedit 是由于 wepy 在 build 的时候丢掉了 weapp.engine.io/lib/transports 目录, 原因暂时还没查明, 可以给 wepy 提 issue.

**Comment by notedit** [comment]
https://github.com/Tencent/wepy/issues/1312

**Comment by gongzili456** [comment]
请使用 `npm i weapp.socket.io` 安装即可
