### ISSUE TITLE
微信小程序使用socket.io连接php原生socket

### ISSUE THREAD

**Issue by lxljl** [10cella/weapp.socket.io#20]
小程序中 使用 socket.io  ，连接php服务器中原生的socket ，连接不成功 返回连接超时 ，和连接失败！
小程序中 如果使用原生的socket ， 可以连接到php服务器，返回成功，这是什么原因？

**Comment by gongzili456** [comment]
socket.io 是基于 原生 websocket 协议的再封装，不可以直接和原生 webosocket 协议直接通信的。

**Comment by lxljl** [comment]
> socket.io是基于原生websocket协议的再封装，不可以直接和原生webosocket协议直接通信的。
好的，谢谢

**Comment by WKlili** [comment]
可以使用weapp.socket.io。
