### ISSUE TITLE
wepy框架中 wepy build编译会报错

### ISSUE THREAD

**Issue by jingxinxin** [10cella/weapp.socket.io#21]
![image](https://user-images.githubusercontent.com/6293249/45548573-5f93fe00-b857-11e8-9499-1311540a043e.png)

**Comment by gongzili456** [comment]
在 wepy 等支持 npm 的框架中，请使用 `npm i weapp.socket.io` 安装模块，

```
import io from 'weapp.socket.io'

const socket =  io('http://localhost:3000')
```

**Comment by jingxinxin** [comment]
@gongzili456 正是这样使用的

> socket.js

```javascript
export let socketURL = 'ws://xxx.com'
if (__DEV__) socketURL = 'ws://localhost:3000'

import io from 'weapp.socket.io' 

export default io
```
> index.js
```
  import io, { socketURL } from '../config/socket'

const socket = io(socketURL, {
        query: {
          token: xxx
        }
      })
```

**Comment by jingxinxin** [comment]
@gongzili456 我的意思就是我一开始就是这样使用的，编译会报错

> wepy.config.js
```javascript
...
module.exports.plugins = {
    uglifyjs: {
      filter: /\.js$/,
      config: {}
    },
    imagemin: {
      filter: /\.(jpg|png|jpeg)$/,
      config: {
        jpg: {
          quality: 80
        },
        png: {
          quality: 80
        }
      }
    }
  }
...
```
我自己排查了一下，这里把gulifyjs 压缩去掉就不会报错了
问题是：其它代码是需要压缩的，看来只有过滤压缩你的包才行了

**Comment by jingxinxin** [comment]
> @gongzili456 我的意思就是我一开始就是这样使用的，编译会报错
> 
> 我自己排查了一下，这里把uglifyjs 压缩去掉就不会报错了
> 问题是：其它代码是需要压缩的，看来只有过滤压缩你的包才行了
> 
> > wepy.config.js
> 
> ```js
> ...
> module.exports.plugins = {
>     uglifyjs: {
>       filter: /\.js$/,
>       config: {}
>     },
>     imagemin: {
>       filter: /\.(jpg|png|jpeg)$/,
>       config: {
>         jpg: {
>           quality: 80
>         },
>         png: {
>           quality: 80
>         }
>       }
>     }
>   }
> ...
> ```

### 解决方案
#### 1. 过滤文件
filter后面的正则表达式可以改成` /^((?!weapp.socket.io).)*\.js$/ `或者` ^(?!a\.js$)+\.js$`

#### 2. 尝试其它库
#5 此Issues 有提到一个库
https://github.com/cytle/socket.io-mp-client

**Comment by gongzili456** [comment]
@jingxinxin 按照你的配置，使用 wepy 框架完全正常。你可以看我的 wepy 的 [Demo](https://github.com/weapp-socketio/wepy-demo-socket.io)，可以检查看有何异同。

**Comment by laravuel** [comment]
我也遇到这个问题了，build时候报这个错误

**Comment by luy19** [comment]
The same question for me, I solve it in the following way:
> wepy.config.js
```
...
module.exports.plugins = {
    uglifyjs: {
      filter: /^((?!weapp.socket.io).)*\.js$/,
      config: {},
    },
...
}
```
