### ISSUE TITLE
Cannot set property 'socketTaskId' of null

### ISSUE THREAD

**Issue by niefang2017** [10cella/weapp.socket.io#23]
微信小程序上报这个错
Cannot set property 'socketTaskId' of null
on wechatReporting this error at WeChat

**Comment by gongzili456** [comment]
请展示您的代码，方便我们排查

**Comment by niefang2017** [comment]
const io = require('../utils/weapp.socket.io.js')
let socket = null
let url = null;
function createConnect(conn = { url: "", room:"socketRoom",response:()=>{},onLine:()=>{},onClose:()=>{},onError:()=>{},onSystem:()=>{}}) {
  url = conn.url
  socket = (this.socket = io(
    url,
    {
      query: {
        room: conn.room,
        userId: `client_${Math.random()}`,
      },
      transports: ['websocket']
    }
  ))
  console.log("socket",socket)
  const id = socket.id
  socket.on('connect', () => {
  })
  socket.on(id, msg => {
    conn.response(msg)
  });
  socket.on('online', (msg) => {
    conn.onLine(msg)
  })
  socket.on('system', (msg) => {
    conn.onSystem(msg)
  })
  socket.on('disconnect', msg => {
    conn.onClose(msg)
  });
  socket.on('error', (e) => {
    conn.onError(e)
  });
}
function closeSocket(){
  if (this.socket) {
    this.socket.close()
    this.socket = null
    wx.closeSocket({
      url: url,
      success: () => {
        console.log("socket close success")
      }
    })
  }
}
module.exports={
  createConnect: createConnect,
  closeSocket: closeSocket
  
}

**Comment by niefang2017** [comment]
调用 
webSocket.createConnect({
      url: 'socket的url',
      room: room,
      response: (res) => {
        console.log("res:", res);
      },
      onLine: (msg) => {
        console.log("online:", msg)
      },
      onError: (err) => {

      },
      onClose: (e) => {

      },
      onSystem: (msg) => {
        console.log("system", msg)
        if (msg.type == 'update' && msg.success) {
          
        }
      }
    }) @gongzili456

**Comment by gongzili456** [comment]
本项目在内部管理力 websocket 的连接状态（open，close等），请不要再使用 wx API 管理连接，你不应该自己定义 `closeSocket` 方法来主动关闭连接。如需主动关闭请参考如下代码：

```
const socket = io(wx://example.com)
socket.disconnect()
```
