### ISSUE TITLE
Can weapp.socket.io also support baidu-mini-app(百度) and ali-mini-app（支付宝）？

### ISSUE THREAD

**Issue by Andrewuetyang** [10cella/weapp.socket.io#25]

**Comment by gongzili456** [comment]
ali-mini-app will be support

**Comment by domingoxx** [comment]
请问下， 支持微信小游戏吗？

**Comment by Noemi-** [comment]
It seems that weapp.socket.io can be also worked in baidu-mini-app.

**Comment by xeoshow** [comment]
> ali-mini-app will be support

Is this supported now? Thanks

**Comment by fanweixiao** [comment]
不支持，有需要的请fork了自己创建。结束这个issue。
