### ISSUE TITLE
服务器端使用  netty-socketio 后有bug

### ISSUE THREAD

**Issue by gogym** [10cella/weapp.socket.io#27]
如果服务器端使用  netty-socketio（java语言）。连接如果指定namespace的话(path:"/abc")，会出错，无法连接成功。希望作者可以看看:failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by javacodekit** [comment]
> 如果服务器端使用 netty-socketio（java语言）。连接如果指定namespace的话(path:"/abc")，会出错，无法连接成功。希望作者可以看看:failed: Error during WebSocket handshake: Unexpected response code: 400

新版本已经解决了。
