### ISSUE TITLE
当多个页面共享socket.io时，会出现微信小程序 同时最多发起 2 个 socket 请求 

### ISSUE THREAD

**Issue by Freddoctor** [10cella/weapp.socket.io#29]
const socket = require("../../utils/socket.js")
socket.connect((status, ws) => {
      this.ws = ws;
      ws.close();
      ws.open();
      ws.emit('quotationH5', {
        "secret": "h5Socket",
        "appType": "h5"
      })
      console.log(ws)
      ws.on('quotationPushH5', res => {
        console.log(res);
        var data = JSON.parse(res);
        var quotation = null;
        for (var key in data) {
          quotation = key
        }
         _this.setData({
           key:quotation,
           value: data[quotation]
         })
      })
    })

**Comment by gongzili456** [comment]
微信对连接数有限制，请考虑利用 Namespace & Room 的特性来重用连接，并将 socket 实例对象在小程序全局共享，避免创多次建多个连接。
