### ISSUE TITLE
怎么请求参数里面怎么不带sid

### ISSUE THREAD

**Issue by q98765543221** [10cella/weapp.socket.io#32]
![image](https://user-images.githubusercontent.com/17985599/49349416-770bb600-f6e5-11e8-8180-8070306f9a99.png)

web端用的socket.io-client是带sid与后台连接的,小程序里面用的这个不带sid,好像连不上服务端

**Comment by hexiaoyanh** [comment]
同样的问题

**Comment by gongzili456** [comment]
sid 不是在客户端发起请求的时候产生的，而是 Server 端在握手之后返回的，下图是 socket.io 官网的连接示例：
![image](https://user-images.githubusercontent.com/6082335/76047011-70c95100-5f9c-11ea-96c9-7547b93cb220.png)

![image](https://user-images.githubusercontent.com/6082335/76046997-67d87f80-5f9c-11ea-95ee-21d9a6d21e21.png)
