### ISSUE TITLE
发送的数据不支持 ArrayBuffer 类型

### ISSUE THREAD

**Issue by eyasliu** [10cella/weapp.socket.io#33]
发送 ArrayBuffer 数据时发现是发的空包过去，示例代码
```js
const ws = io('ws://127.0.0.1:8092', {
  forceNew: true,
  reconnection: false,
})
ws.open()
ws.on('connect', () => {
  const buffer = (new TextEncoder()).encode(JSON.stringify({hello: 'world'})).buffer
  ws.emit('DATA', buffer)
})
```
在 Frames 看到发送的数据实际上是 `["DATA", {}]`，buffer 数据全丢了，所以猜测是不是目前还没有支持 ArrayBuffer

**Comment by eyasliu** [comment]
clone 了最新代码本地构建一个版本，出现了其他问题，发送一个 ArrayBuffer 实际上会发两个请求，这没问题，官方库也是如此
第一次发的是：`451-["BRIDGE",{"_placeholder":true,"num":0}]` length=44
第二次发的是:：`4[object ArrayBuffer]` length=21

我以为真的发了arrayBuffer，突然想到 `"4[object ArrayBuffer]".length === 21` 所以其实还是没有发送真实的ArrayBuffer

**Comment by shengbiaoguo** [comment]
遇到同样的问题，发送ArrayBuffer数据丢失

**Comment by gongzili456** [comment]
从您的代码来看，你的 buffer 变量实际上是一个 ArrayBuffer 实例，是一个字节数组的包裹对象，无法直接操作内部的数据，需要转换成类型数组对象，比如：Int8Array，Uint8Array等。
参见：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

可修改为
```
data = new Uint8Array(buffer)
ws.emit('DATA', data)
```
