### ISSUE TITLE
页面报错请问是什么原因？

### ISSUE THREAD

**Issue by 847721464** [10cella/weapp.socket.io#35]
![_20190107115555](https://user-images.githubusercontent.com/20931278/50748266-767db680-1273-11e9-9ced-26417e57e0b9.png)
![_20190107115544](https://user-images.githubusercontent.com/20931278/50748267-77164d00-1273-11e9-8d7a-7f87b7e2cd04.png)

**Comment by gongzili456** [comment]
请将问题细节描述清楚

**Comment by 847721464** [comment]
请问这是什么原因？在chrome44下面打开的

**Comment by gongzili456** [comment]
您是如何使用的呢？比如如何编译的，在什么环境中 run ，如何引入的代码等？请详细描述下。

**Comment by 847721464** [comment]
页面main.js，import socketio from 'weapp.socket.io',
我使用的是mpvue开发的
 socket.on('disconnect', d => {
        console.log('断开')
      })
      socket.on('connect', () => {
        
      })
      socket.on('chatevent', (data) => {
        console.log('连接成功6',data)
       
      });
      socket.on('reconnecting', data => {
        console.log(data, 6566)
      })

是按正常的开发的，好像低版本的chrome44以下就打不开，其他都可以的

**Comment by gongzili456** [comment]
本项目只能在小程序环境中使用。

**Comment by 847721464** [comment]
好吧
