### ISSUE TITLE
socket query第二次连接时无法更新

### ISSUE THREAD

**Issue by DelCoding** [10cella/weapp.socket.io#36]
代码如下，当第二次连接指定query时， socket无法更新   
```  js
socket = io(socket_url + roomid, {
    query: "openid=" + openid + "&sessionid=" + sessionid,
    upgrade: false,
    transports: ['websocket']
});
socket.connect()
```

**Comment by gongzili456** [comment]
query 参数只能在握手期间传递，在连接Room的时候无法传递query参数。

**Comment by gongzili456** [comment]
当利用namespace做第二次连接的时候是可以传递query对象的，

**Comment by gongzili456** [comment]
当第二次利用 Room 来做连接的时候，传递 query 对象是可行的，可以在 handshake.header 拿到数据：
![image](https://user-images.githubusercontent.com/6082335/76048010-74aaa280-5f9f-11ea-9acd-c947d819dd80.png)
