### ISSUE TITLE
连接不能带目录wss://wsswxapp.ccc.com/chess

### ISSUE THREAD

**Issue by meikang123** [10cella/weapp.socket.io#38]

**Comment by gongzili456** [comment]
请确定你的 server 监听在了这个 path 吗？

**Comment by meikang123** [comment]
监听了  并且都连接成功了   心跳起来了  我这边消息发不出去
![qq 20190304211502](https://user-images.githubusercontent.com/16129828/53735679-98399980-3ec2-11e9-8dc7-8552d325a338.png)

**Comment by gongzili456** [comment]
该 path 默认是当做了namespace ，请确定 server 端对应了该公司namespace
