### ISSUE TITLE
小程序只支持ws(s)，并不支持http(s)，所以在生产环境下跑不通啊，求解答

### ISSUE THREAD

**Issue by KDSER** [10cella/weapp.socket.io#42]
小程序只支持ws(s)，并不支持http(s)，所以在生产环境下跑不通啊，求解答

**Comment by gongzili456** [comment]
本项目是将小程序支持的原生 WebSocket 协议封装成 socket.io 协议，并不存在你说的 http 问题。

**Comment by KDSER** [comment]
抱歉，理解错误了
