### ISSUE TITLE
在android10上可能有点问题

### ISSUE THREAD

**Issue by hnxzc** [10cella/weapp.socket.io#49]
`从客户端日志看到的情况是：

14:36:48.318 收到 connectSocket 调用

14:36:48.505 抛了 open 事件

14:37:13.511 收到 send 调用

所以这里的问题在于前端收到 open 事件之后，等待了 15s 才调用 send 接口。从你贴的代码看到，你是用了 socket.io 这个库。按你的预期，应该是调用了 socket.emit 之后就会去调用底层的 send 接口，但实际上没有。

具体原因需要你进一步排查，建议不用 socket.io 这个库，直接用原生接口尝试下是否还有这个问题。如果问题不存在了，说明是 socket.io 内逻辑异常；如果问题还存在，再提供日志我们这边定位一下。`
以上是微信官方给的答复，问题详见https://developers.weixin.qq.com/community/develop/doc/00008ef30205a02b81791310356800

**Comment by hnxzc** [comment]
使用原生接口，收到open事件后能够立马调用send接口，没有延迟，作者能否升级一下socket.io版本？

**Comment by JOU-amjs** [comment]
这些天我也碰到了和你一样的情况，一开始我也觉得是7.0.8版本的websocket有问题，分析weapp.socket.io源码发现是因为微信7.0.8版本内会先接收onMessage的open消息，后面才接收onOpen消息（7.0.8以前的版本是onOpen先执行），导致的执行顺序出问题了。
所以找到问题后就很好改了，在onMessage回调上做一下延迟执行即可，代码如下：
```javascript
   this._socket.onMessage(data => {
      setTimeout(() => {
        this.onmessage(data)
      }, 0);
    })
```

**Comment by hnxzc** [comment]
> 这些天我也碰到了和你一样的情况，一开始我也觉得是7.0.8版本的websocket有问题，分析weapp.socket.io源码发现是因为微信7.0.8版本内会先接收onMessage的open消息，后面才接收onOpen消息（7.0.8以前的版本是onOpen先执行），导致的执行顺序出问题了。
> 所以找到问题后就很好改了，在onMessage回调上做一下延迟执行即可，代码如下：
> 
> ```js
>    this._socket.onMessage(data => {
>       setTimeout(() => {
>         this.onmessage(data)
>       }, 0);
>     })
> ```

这样啊，我把前端用微信小程序原生接口全部重写了。。。
