### ISSUE TITLE
使用wss协议自动转成https协议

### ISSUE THREAD

**Issue by Andrewuetyang** [10cella/weapp.socket.io#6]
在微信小程序中使用wss协议，会被转https协议，是否意味着不能使用wss协议？

**Comment by gongzili456** [comment]
socket.io 会首先创建基于HTTP的长轮训连接，然后检查是否满足条件切换至 WS 协议的连接。

你可以查看 websocket 连接有没有创建成功。
如果失败请确认server端服务是否健康， Nginx 配置是否正确。
