### ISSUE TITLE
真机测试时 一直触发重连 reconnecting

### ISSUE THREAD

**Issue by likaixuan** [10cella/weapp.socket.io#9]
微信开发者工具中正常

**Comment by gongzili456** [comment]
请详细描述一下使用方式，或者截图log

**Comment by gongzili456** [comment]
访问  socket.io 官网，打开WEB控制台，执行一下代码 `io('wss://wss.moegezi.cn')` 验证确实是无法连接成功的，请检查你的Server端服务是否正常

**Comment by likaixuan** [comment]
老哥能把他换成xx吗 地址不小心漏了

**Comment by gongzili456** [comment]
@likaixuan 检查下你的 Server 吧

**Comment by likaixuan** [comment]
非常感谢您，这个问题应该是我们的证书过期导致的
